server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    location = / {
        return 302 /chipverse-pwa/;
    }

    location /chipverse-pwa/ {
        rewrite ^/chipverse-pwa/(.*)$ /$1 break;
        try_files $uri $uri/ /index.html;
    }
}